# allows docker containers to be used for builds
sudo: false

language: java

jdk:
  - oraclejdk8

script:
  - mvn install -DskipTests
  - mvn integration-test

before_cache:
  - rm -f $HOME/.m2/repository/net/raboof/play

cache:
  directories:
  - $HOME/.m2